name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-220.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icono.png"
  android: true
  ios: true